services:
  postgres:
    image: postgres:16
    volumes:
      - ./database/.data/postgres:/var/lib/postgresql/data
    env_file:
      - ./localstack/localstack.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - shared_network
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      AWS_ACCESS_KEY_ID: ${APP_AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${APP_AWS_SECRET_KEY}
      AWS_REGION: ${APP_AWS_REGION}
      AWS_ENDPOINT_URL: ${DEV_AWS_ENDPOINT}
    ports:
      - 4567:4566
    volumes:
      - "./localstack/localstack-init:/etc/localstack/init/ready.d"
    env_file:
      - ./localstack/localstack.env
    networks:
      - shared_network

  tts-webui:
    build:
      dockerfile: ./tts-webui/TTS-WebUI.Dockerfile
    ports:
      - "7778:7778"
      - "7770:7770"
      - "3000:3000"
    volumes:
      - ./tts-webui/tts_models:/root/.cache/huggingface
      - ./tts-webui/tts_voices:/app/tts-webui/voices
    env_file:
      - ./tts-webui/tts-webui.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - shared_network

  chainlit:
    build:
      context: ./chainlit
      dockerfile: ./chainlit.Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - ./chainlit/:/app
      - ./chainlit/ssl:/app/ssl
      - ./chainlit/uploads:/app/uploads
    env_file:
      - ./chainlit/chainlit.env
    depends_on:
      - postgres
      - localstack
      - ollama
      - tts-webui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - shared_network

  ollama:
    build:
      dockerfile: ./ollama/Ollama.Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama_data:/root/.ollama
      - ./ollama/ollama_app:/app
    env_file:
      - ./ollama//Ollama.env
    environment:
      - OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH:-4096}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - shared_network

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/config/passwd
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

volumes:
  tts_models: